canonical/microk8s-core-addons

addons/mayastor/chart/values.yaml
Disable device validation instead of checking local hostpath for the file.
=> Disable device validation on mayastor-msp-operator

addons/hostpath-storage/storage.yaml
Update hostpath-provisioner to use temporary busybox pods to provision volumes. This allows the provisioner to work correctly in multi-node MicroK8s clusters.
Needs https://github.com/juju-solutions/hostpath-provisioner/pull/3
=> Upgrade hostpath-provisioner to 1.2.0

addons/mayastor/disable, addons/mayastor/enable
Fixes #14
Do not preserve the mayastor image files by default when disabling the addon
=> Delete image files when disabling mayastor by default

addons/mayastor/chart/values.yaml
Update etcd-operator image to include https://github.com/canonical/etcd-operator/commit/2c19720af76c912ca75b75bcd850c6ba267a5b4d
This is required since #6 has silently affected how DNS resolution works for not ready addreses.
=> Update etcd-operator image to include DNS resolution fixes

addons/mayastor/chart/values.yaml
Fixes #12 
Increase number of retries for mayastorpool creation loop. This prevents issues with mayastor pools failing to come up because mayastor is still being deployed.
=> Increase number of msp creation retries in mayastor addon

addons/dns/disable
Sometimes the restart of the services was taking longer than the scheduling of the k8s resource deletion. this was causing the coredns pod to stay in "Terminated" state.
=> Improve the teardown of dns

addons.yaml, addons/ingress/enable
The [new version 1.2.0](https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v1.2.0) of the ingress controller includes some security fixes. This PR bumps the version that will be used by the ingress microk8s addon.
In order to test it, I have done the following:
- Snapcraft build microk8s locally pointing to my forked repo with the 1.2.0 ingress version.
- Enable the ingress addon
```bash
$ microk8s enable ingress
```
- Check that indeed the right version was installed with:
```bash
$ microk8s kubectl get pods -n ingress -oyaml | grep -i image: | grep ingress
image: k8s.gcr.io/ingress-nginx/controller:v1.2.0
```
- I check that it works by exposing a node port service:
```bash
$ microk8s kubectl create deployment server-gog -n ingress …
```
=> Bump ingress version that fixes CVEs 

addons.yaml, addons/mayastor/chart/values.yaml, addons/mayastor/enable
Add arm64 support for the mayastor addon.
- We keep using images under cdkbot until upstream has multi-arch release image tags.
- We keep using the helm charts from our fork, until our changes get merged upstream.
- The mayastor-msp-operator image contains this change, not yet merged upstream https://github.com/openebs/mayastor-control-plane/pull/251
If you don't have an arm64 machine handy, get one from AWS:
```
juju add-machine --constraints 'arch=amd64 mem=4G root-disk=40G cores=4'
juju ssh 0
```
Dependencies:
```
sudo apt-get install linux-modules-extra-$(uname -r)
sudo modprobe nvme-tcp
sudo sysctl vm.nr_hugepages=1024
```
Installation:
```
sudo snap install microk8s --classic --channel 1.24
sudo microk8s addons repo add core https://github.com/canonical/microk8s-core-addons …
```
=> Support mayastor addon on arm64 architectures

addons/dashboard/enable
Since v1.24 tokens do not get created automatically for SA. With this PR we ask the user to create a token for accessing the dashboard.
=> Update the login instructions for accessing the k8s dashboard

addons/metallb/metallb.yaml
To suppress:
Warning: spec.template.spec.nodeSelector[beta.kubernetes.io/os]: 
deprecated since v1.14; use "kubernetes.io/os" instead
=> [metallb] nodeSelector deprecation warning

addons/gpu/enable
Update GPU operator to version 1.10.1
Closes #34 
Closes https://github.com/canonical/microk8s/issues/3218
Install and test on an AWS `g3s.xlarge` instance. Without this change, the GPG key error comes up. With this change, the driver is properly built and loaded:
<details>
<pre>
root@ip-172-31-12-67:/home/ubuntu# microk8s.kubectl logs -n gpu-operator-resources nvidia-driver-daemonset-2thc7
Defaulted container "nvidia-driver-ctr" out of: nvidia-driver-ctr, k8s-driver-manager (init)
DRIVER_ARCH is x86_64
Creating directory NVIDIA-Linux-x86_64-510.47.03
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 510.47.03..................................................................................................................................... …
=> Update GPU operator

addons.yaml, addons/gpu/disable, addons/gpu/enable
Rework GPU addon. Adds lots of new options:
The simple way to enable the addon is still available and works as it should: `microk8s enable gpu`
- Fix regression when removing the GPU addon introduced by #44 
- Check that the host drivers are installed using `nvidia-smi` instead of `lsmod | grep nvidia`.
- Fix the containerd configuration file being passed to the nvidia container toolkit daemonset with a fixed revision number
- Support passing custom configuration values to the gpu-operator helm chart
- Support manual restart of containerd (this is mostly meant for usage in 1.21)
Note that this comes with a number of updates to the [documentation page](https://microk8s.io/docs/addon-gpu)
Tested following scenarios:
- 1.21 with host drivers (`--no-backwards-compatible …
=> Rework GPU addon

addons/hostpath-storage/storage.yaml, addons/mayastor/chart/values.yaml
Our addons currently use different versions of busybox. Update to always use the same pinned version.
```
$ microk8s addons repo add core https://github.com/canonical/microk8s-core-addons --reference MK-591/pin-busybox-images --force
$ microk8s enable storage mayastor
```
wait for pods to come up, ensure only `busybox:1.34.1-glibc` is used:
```
$ microk8s ctr image ls -q | grep busybox
docker.io/library/busybox:1.34.1-glibc
docker.io/library/busybox@sha256:db203ccc233573e1db3737553e7b511000412306a1420c7f512377e1a5702786
```
=> Pin busybox images to 1.34.1-glibc

tests/test-addons.py
Added a `skipif` based on `STRICT` env variable for the gpu tests in strict since they are expected to fail
Add `STRICT="yes"` to the environment variables before calling `pytest`. E.g.
```
sudo STRICT="yes" pytest -s /var/snap/microk8s/common/addons/core/tests/test-addons.py
```
=> Added a strict skipif to skip gpu tests

addons.yaml
Set the confinement property of the GPU addon to "classic" so it is not available in the strict builds.
=> Set the confinement flag of the gpu addon

addons.yaml, addons/helm/disable, addons/helm/enable, addons/helm3/disable, addons/helm3/enable, addons/observability/disable, addons/observability/enable
Sibling PR for https://github.com/canonical/microk8s/pull/3324
Starting from MicroK8s 1.25, helm comes pre-installed with the snap.
- The `helm` and `helm3` are kept and always appear as enabled. This is to maintain backwards compatibility for downstream usage of `microk8s enable helm3`
- Update the addon version to match the helm binary version
=> Helm comes pre-installed with MicroK8s

.github/workflows/check-formatting.yml, .prettierignore
This PR uses the `.prettierignore` file to consolidate all the `yaml` files we don't want prettier to check.
=> use prettier ignore file to ignore yamls we dont want to check

addons.yaml
Ensure `observability` addon is not shown as enabled as a false positive any time a pod with name prometheus exists.
=> fix enabled check for observability addon

addons/hostpath-storage/storage.yaml
Backport https://github.com/canonical/microk8s-core-addons/pull/73 to 1.24
=> [Backport 1.24] Update hostpath-provisioner to 1.3.0

addons/hostpath-storage/storage.yaml
Update hostpath-provisioner version to 1.3.0
- includes reduced resource limits for provisioner pod (https://github.com/canonical/hostpath-provisioner/pull/4)
- includes support for ppc64le (https://github.com/canonical/hostpath-provisioner/pull/6)
=> Update hostpath-provisioner to version 1.3.0 

addons.yaml
Add support for `ppc64le` architecture on supported addons.
- Add `ppc64le` in list of supported_architectures for addons that already have `ppc64le` support
- Update registry to 2.8.1, adding support for s390x and ppc64le
=> ppc64le architecture support

addons/registry/registry.yaml
Followup for #79, missed the actual update of the image used for the registry pod.
=> Update registry to 2.8.1

addons.yaml
Update versions of kubernetes-dashboard (has been upgraded to 2.6.0) and hostpath-provisioner (has been upgraded to 1.3.0)
=> Update addon versions to match installed one

addons/dashboard/dashboard.yaml
Update dashboard to 2.7.0 to fix compatibility issues with Kubernetes 1.25
=> (Backport 1.25) Update dashboard to 2.7.0

addons/dashboard/dashboard.yaml
Upgrade kubernetes dashboard to 2.7.0 to improve support for Kubernetes 1.25
=> Update dashboard to 2.7.0

addons/gpu/enable
Closes https://github.com/canonical/microk8s/issues/3452
Update GPU operator to version [v22.9.0](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/release-notes.html), fixing support for 1.25
=> Update GPU operator to v22.9.0

addons/dns/enable, tests/validators.py
Rework how upstream nameservers are chosen in the DNS addon. Review along with the sibling PR https://github.com/canonical/microk8s/pull/3487.
Currently, MicroK8s hardcodes upstream nameservers to 8.8.8.8 and 8.8.4.4. This is not always desirable, because:
- The nameservers may not be reachable in airgap deployments, enterprise environments, etc.
- Breaks name resolution for local hostnames.
We change the behaviour to the following, with the aim of maintaining backwards compatibility whenever possible, but also ensuring that the host resolv.conf file is used when available.
| enable command                           | old behaviour                                  | new behaviour …
=> Rework how upstream nameservers are chosen in the DNS addon

addons/kube-ovn/ovn-template.yaml
Remove PodSecurityPolicy from resources, update RBAC
Related PRs are https://github.com/kubeovn/kube-ovn/pull/1822 and https://github.com/charmed-kubernetes/charm-kube-ovn/pull/28
=> Update KubeOVN RBAC rules, fix compatibility with 1.25

addons/ha-cluster/disable, addons/ha-cluster/enable
We need to call the python scripts without preserving the env variables in strict.
=> Fix the enable and disable ha-cluster addons on strict

addons.yaml, addons/hostpath-storage/storage.yaml
Includes https://github.com/canonical/hostpath-provisioner/pull/8
=> Bump hostpath-provisioner to 1.4.2

addons/observability/enable
- Configure the scheduler and the controller-manager to authentify and to
authorize the incoming requests.
- Configure the kube-proxy endpoints and make it listen to the metrics
requests on all interfaces
Fixes canonical/microk8s#2379.
Before:
After:
=> Observability: fix Kubernetes components monitoring

addons.yaml, addons/ingress/enable, addons/ingress/ingress.yaml
The new version 1.5.1 of the ingress controller includes some security fixes. This PR bumps the version that will be used by the ingress microk8s addon.
In order to test it, I have done the following:
- Snapcraft build microk8s locally pointing to my forked repo with the 1.5.1 ingress version.
- Enable the ingress addon
```
$ microk8s enable ingress
```
- Check that indeed the right version was installed with:
```
$ microk8s kubectl get pods -n ingress -oyaml | grep -i image: | grep ingress
image: registry.k8s.io/ingress-nginx/controller:v1.5.1
```
-  I check that it works by exposing a node port service:
```
$ microk8s kubectl create deployment nginx -n ingress --image=nginx --port 80
$ microk8s kubectl expose -n ingress deployment nginx --type=NodePort 
$ microk8s kubectl get svc  -n …
```
=> Upgrade ingress to 1.5.1 to address cve

addons/hostpath-storage/enable
Added warning to state the limitation of hostpath storage addon to not follow the size set by users, which can sometimes go beyond the set size limit too.
=> Add warning for hostpath storage size limitation

addons/metallb/enable
Closes https://github.com/canonical/microk8s/issues/3496
QOL changes to metallb enable script.
=> minor fixes to metallb addon enable script

tests/test-addons.py, tests/utils.py
We want to allow to run the GPU tests on VMs. We also want to allow the test to load the kernel drivers if needed.
It is a backport of the work done on the main branch https://github.com/canonical/microk8s-core-addons/commit/e262eda0a3561007ca1866a2b2f6d974a3f8d79f
=> Run GPU tests on VMs but not on lxc

addons/dns/enable, addons/metrics-server/enable, addons/rbac/enable
Do not restart services if they already had the correct configuration flags.
Also adding a note for future reference, in case we see issues arising from this.
=> Skip needless service restarts when enabling addons

addons/observability/disable, addons/observability/enable, addons/observability/grafana.yaml
- allow the user to specify custom Helm values for all the charts
installed by this addon
- allow the user to set the chart version to deploy, by default the
latest one is picked
- make Tempo optional
=> Observability addon improvements

addons/dns/coredns.yaml, tests/test-addons.py
Update CoreDNS to 1.10.0.
Update coredns tests as well now that we enable DNS by default on new clusters
=> Bump CoreDNS to 1.10.0

.github/workflows/run-tests.yml, tests/test-addons.py
use subprocess instead of `sh` for testing addons.
we do not require any extra sh features, stick to the standard library. also, `sh` came out with version 2.0.0 which breaks our CI
=> Drop sh from tests

addons/metallb/enable
Wait for MetalLB to come up and ensure address pool and L2 advertisements are properly created when enabling metallb.
=> ensure metallb addon properly creates the address pool

addons/metallb/enable
=> [Backport 1.26] ensure metallb addon properly creates the address pool

addons/common/utils.sh
Ensure a unique temporary file is used when applying addon manifests.
=> Ensure a unique temporary file is used for manifests

addons.yaml, addons/mayastor/chart/Chart.yaml, addons/mayastor/chart/README.md, addons/mayastor/chart/TROUBLESHOOTING.md, addons/mayastor/chart/templates/mayastor-rbac.yaml, addons/mayastor/chart/templates/mayastor-sa.yaml, addons/mayastor/chart/values.yaml, addons/mayastor/disable, addons/mayastor/enable, addons/mayastor/pools.py
Upgrade mayastor addon to version 2.0.0
- Update to new helm chart https://github.com/openebs/mayastor-extensions, forked at https://github.com/canonical/mayastor-extensions. The helm chart is released at https://github.com/canonical/mayastor-extensions/releases/tag/v2.0.0-microk8s-1
- Change MayastorPool references to DiskPool (change in mayastor 2.0.0)
- Update addon build instructions for new helm charts, fix build instructions, add troubleshooting tips and add instructions for multi-arch images
- Adjust values.yaml file for the new helm chart
- Add a `microk8s mayastor-pools` helper command that can be used to easily manage pools in the cluster.
=> Upgrade Mayastor to version 2.0.0

addons/metallb/metallb.yaml
MetalLB images are no longer available on DockerHub.
=> [1.24] pull metallb images from quay.io

addons/mayastor/enable
Updated addon to pass correct value to [helm chart](https://github.com/canonical/microk8s-core-addons/blob/99954f9175615397ee12f6a1c4d4a9b2c6606cd2/addons/mayastor/chart/values.yaml#L115) for image size.
=> Update mayastor addon to pass correct value to helm chart for image size

addons/cert-manager/enable
No functional changes. Fixes the following output:
```bash
Then, you can create an ingress to expose 'my-service:80' on 'https://my-service.example.com' with:
$ microk8s enable ingress
$ microk8s kubectl create ingress my-ingress     --annotation cert-manager.io/cluster-issuer=letsencrypt     --rule 'my-service.example.com/*=my-service:80,tls=my-service-tls'
```
to:
```bash
Then, you can create an ingress to expose 'my-service:80' on 'https://my-service.example.com' with:
$ microk8s enable ingress
$ microk8s kubectl create ingress my-ingress \
--annotation cert-manager.io/cluster-issuer=letsencrypt \
--rule 'my-service.example.com/*=my-service:80,tls=my-service-tls'
```
=> Fix formatting of cert-manager addon enable script

addons/cis-hardening/README.md, addons/cis-hardening/disable, addons/cis-hardening/enable, tests/validators.py
This PR enables the CIS addon to switch away from the tokens based auth.
The work on the enable/disable hooks will not run on 1.28 snap as that snap will ship without token auth by default. The work on the hooks is only relevant to snaps that got refreshed to the 1.28 version.  
This PR also includes updates on the README on how to configure a pre 1.28 node not to use auth tokens.
=> CIS tokens patch

addons/cis-hardening/README.md, addons/cis-hardening/enable
This PR introduces a `--install-kubebench` flag that skips the installation of kubebench. This is useful in offline deployments.
=> Flag to skip kubebench download and install in cis hardening

addons/cis-hardening/cfg/cis-1.24-microk8s/etcd.yaml
The `test` may not be under `/bin/`. This PR fixes the test failure in our CI and improves the wording in the 2.4 test.
=> Assume test in the user path

addons/metrics-server/metrics-server.yaml
When enabling the metrics server under RBAC we get the metrics-server pod not getting to Ready state. The error it reports is:
```
E0710 15:22:18.750492       1 scraper.go:140] "Failed to scrape node" err="request failed, status: \"403 Forbidden\"" node="ip-172-31-3-156"
I0710 15:22:25.658360       1 server.go:187] "Failed probe" probe="metric-storage-ready" err="no metrics to serve"
```
The logs of kubelite look like this:
```
Jul 10 15:23:14 ip-172-31-3-156 microk8s.daemon-kubelite[1426885]: E0710 15:23:14.966647 1426885 controller.go:113] loading OpenAPI spec for "v1beta1.metrics.k8s.io" failed with: Error, could not get list of group versions for APIService
Jul 10 15:23:14 ip-172-31-3-156 microk8s.daemon-kubelite[1426885]: E0710 15:23:14.966656 1426885 controller.go:116] loading …
```
=> Fix RBAC rules of metrics server

addons/ha-cluster/disable
Because of this: https://github.com/canonical/microk8s/pull/4023 we are not to `microk8s leave` on a single node cluster.
=> Do not leave a single node cluster when disable HA

addons/rook-ceph/plugin/connect-external-ceph
The content interface mounts the microceph config to `$SNAP/microceph/conf`.
=> Correct path for microceph configs

addons/rook-ceph/plugin/connect-external-ceph
Rework how we prepare the osd pool for RBD so that it does not hang if the ceph cluster is not in a healthy state.
- install microk8s from latest edge
- microk8s enable rook-ceph
- snap install microceph --edge
- initialize microceph, but do not add any osds yet
- microk8s connect-external-ceph
Without this change, the command above would hang forever. It now proceeds without issues, and initialization is deferred until OSDs are available in the Ceph cluster.
=> Do not block if ceph cluster is not yet ready

addons/rook-ceph/enable
We have users reporting sudo is needed for calling `microk8s connect-external-ceph` https://discuss.kubernetes.io/t/howto-setup-microk8s-with-micro-ceph-storage/25043/2 . This is probably a permissions problem we need to address. This PR is a small mitigation.
=> Tell users to use sudo when calling the rook-ceph plugin

addons/mayastor/chart/Chart.yaml, addons/mayastor/chart/README.md
Update mayastor to v2.0.0-microk8s-1b, see https://github.com/canonical/mayastor-extensions/releases/tag/v2.0.0-microk8s-1b
Must be backported to 1.27 after merging
=> Update mayastor to v2.0.0-microk8s-1b

.github/workflows/run-tests.yml
We missed this on the 1.28 branch preparation
=> Update run-tests.yml for 1.28-strict

addons.yaml, addons/gpu/disable, addons/gpu/enable, addons/nvidia/disable, addons/nvidia/enable
Rename the `gpu` addon to `nvidia`. Add support for network-operator
- Add flag `--gpu-operator-version` and deprecate `--version`
- Add flag `--gpu-operator-set` and deprecate `--set`
- Add flag `--gpu-operator-values` and deprecate `-f/--values`
- Add flag `--gpu-operator` (default true) to deploy the gpu operator
- Add flag `--network-operator` (default false) to deploy the network operator
- Add flag `--network-operator-version` to choose the network operator version to deploy
- Add flag `--network-operator-set` and `--network-operator-values` to configure the operator
- Rename the gpu addon to nvidia, update the status check
- Keep gpu as an alias for the nvidia addon
1. Backwards compatible deploy and configuration of GPU addon
```
sudo microk8s enable gpu --version 22.9.1
```
2. …
=> Start nvidia addon

addons/cis-hardening/enable
This PR consists of two commits:
* [[cis-hardening] Fix --install-kubebench flag](https://github.com/canonical/microk8s-core-addons/commit/c6a1a2e4ccc6484b92bf160a0c80d8a8af9809ea): To be cherry-picked on 1.28
* [[cis-hardening] Add --skip-kubebench-installation flag](https://github.com/canonical/microk8s-core-addons/commit/a644e2d6fa0465c271842762b93b38f5088eb927) to be released with 1.29
Note: We had `no-kubebench-installation` and `skip-kubebench-installation` in the card - I went for `skip-kubebench-installation` but I don't have a strong opinion on this.
I will create a PR for the branches (e.g. 1.28) after the review of this one.
Closes MK-1388
=> Fix kube-bench installation flag and introduce `--skip-kubebench-installation` 

addons/cis-hardening/enable
The `--install-kubebench` flag is defined without a specific type which let click interpret it as `string`. The check of this flag expected a boolean (`if install_kubebench:...`) which caused
`--install-kubebench="false"` to be evaluated to `True`.
This commit fixes that issue and evaluates the flag correctly. However, we can not simply change the flag type to boolean as this would break the current workaround for this issue (`--install_kubebench=""`). Thus, we maintain the `string` type for this flag for backward-compatibility.
=> [cis-hardening] Fix `--install-kubebench` flag

addons/hostpath-storage/enable, addons/hostpath-storage/storage.yaml
This pull request allows for an additional flag on the hostpath-storage addon to set the deployed yaml to not be the default storage class. This keeps the original functionality of the addon and has been tested with both short and long options independently and combined. This is my first PR, and if there is additional info needed, please let me know! Thanks
=> Adds -d --default-class option to set hostpath-storage

tests/test-addons.py
The test is failing with:
```
Warning  FailedScheduling        77s               default-scheduler        0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
Warning  FailedScheduling        70s               default-scheduler        0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
Normal   Scheduled               68s               default-scheduler        Successfully assigned default/nginx-fs-1 to ip-172-31-13-59
Normal   SuccessfulAttachVolume  68s               attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-e0be2484-53c8-42dc-a63d-2a332162ab7b"
Warning …
```
=> Disable rook-ceph integration testing in strict

addons/nvidia/enable
Fix handling of empty `--gpu-operator-driver` flag
=> nvidia: fix check for gpu driver by default

addons/nvidia/enable
Fixes #269.
I believe the previously intended behavior was to check if the two flags are different, but the default value of `--set-as-default-runtime` was `None`, so the if statement on line 210 evaluated to True by default. Changed it the warning is written whenever the old flag is set to any value, regardless of the new flag.
=> Fix the --set-as-default-runtime deprecation warning

.github/workflows/check-formatting.yml, addons/cert-manager/cert-manager.yaml, addons/cert-manager/enable
As title I did update cert-manager manifest from v1.8.0 to v1.14.5 [manifest](https://github.com/cert-manager/cert-manager/releases/download/v1.14.5/cert-manager.yaml).
*I did*
=> update cert-manager to 1.14.5

addons/ingress/enable
Ingress: Add the ability to specify the `--publish-status-address` via a environment variable when enabling the addon 
Fixes #256 
Usage example:
```bash
PUBLISH_STATUS_ADDRESS=$(curl -4 ifconfig.io) microk8s enable ingress
```
=> Ingress: Add the ability to specify the publish status address

addons/metallb/enable, tests/test-addons.py
This PR allows to use IPv6 ranges or CIDR when enabling metallb addons.
Closes #245
The CLA is requiring informations I do not have... so I cannot sign it.
=> Allow IPV6 ranges for Metallb addon

addons/minio/disable, addons/minio/enable
Minio removed the kubectl krew plugin in 5.0.15, which means that the current workflow for installing the minio addon is outdated and will not work for newer releases.
Updates the minio addon installation to use Helm instead, and brings it up to date.
(cherry picked from commit 1a6aa1bc4107d81f7fa59010ed5f89c170b50211)
This is a backport from: https://github.com/canonical/microk8s-core-addons/pull/290
According to the [MinIO documentation](https://min.io/docs/minio/kubernetes/upstream/operations/installation.html#kubernetes-version-k8s-floor), v6.0.2 is tested against a floor of Kubernetes v1.28.9.
=> Fixes minio addon

addons/minio/disable, addons/minio/enable
Minio removed the kubectl krew plugin in 5.0.15, which means that the current workflow for installing the minio addon is outdated and will not work for newer releases.
Updates the minio addon installation to use Helm instead, and brings it up to date.
This is a backport from: https://github.com/canonical/microk8s-core-addons/pull/290
(cherry picked from commit 1a6aa1bc4107d81f7fa59010ed5f89c170b50211)
According to the [MinIO documentation](https://min.io/docs/minio/kubernetes/upstream/operations/installation.html#kubernetes-version-k8s-floor), v6.0.2 is tested against a floor of Kubernetes v1.28.9.
=> [Backport 1.28] Fixes minio addon

addons/minio/disable, addons/minio/enable
Previously, when the minio krew plugin was used to deploy the minio tenant, the krew plugin created an additional user, with the credentials set in the ``$TENANT_NAME-user-1`` Kubernetes secret.
The Helm chart we're using does not do that by default, but it does accept a list of Kubernetes secrets with ``CONSOLE_ACCESS_KEY`` (user) and ``CONSOLE_SECRET_KEY`` (password) fields set in them.
With this change, we're now creating the secret ourselves, and passing it onto the Helm chart. The minio tenant will have this new user, in addition to the regular root user. With this, the behaviour that the krew plugin had is preserved.
Additionally, remvoes reference to the ``kubectl-minio`` plugin since it doesn't exist anymore.
Please reference the issue this PR is fixing, or provide a description …
=> minio: Adds additional minio tenant user

addons/minio/enable
Previously, when the minio krew plugin was used to deploy the minio tenant, the root user credentials were randomly generated.
The Helm chart we're using have default values: minio, minio123.
We're now generating random strings for the root user and password. Additionally, we're updating the minio env configuration secret name to reflect the tenant name, as it was previously.
=> Updates minio root user and password

addons/minio/disable, addons/minio/enable
Previously, when the minio krew plugin was used to deploy the minio tenant, the krew plugin created an additional user, with the credentials set in the ``$TENANT_NAME-user-1`` Kubernetes secret.
The Helm chart we're using does not do that by default, but it does accept a list of Kubernetes secrets with ``CONSOLE_ACCESS_KEY`` (user) and ``CONSOLE_SECRET_KEY`` (password) fields set in them.
With this change, we're now creating the secret ourselves, and passing it onto the Helm chart. The minio tenant will have this new user, in addition to the regular root user. With this, the behaviour that the krew plugin had is preserved.
Additionally, removes reference to the ``kubectl-minio`` plugin since it doesn't exist anymore.
(cherry picked from commit 8340271ef8930ccc8986779b6aa8eb1096c1cd74) …
=> [Backport 1.28] minio: Adds additional minio tenant user

addons/minio/disable, addons/minio/enable
Previously, when the minio krew plugin was used to deploy the minio tenant, the krew plugin created an additional user, with the credentials set in the ``$TENANT_NAME-user-1`` Kubernetes secret.
The Helm chart we're using does not do that by default, but it does accept a list of Kubernetes secrets with ``CONSOLE_ACCESS_KEY`` (user) and ``CONSOLE_SECRET_KEY`` (password) fields set in them.
With this change, we're now creating the secret ourselves, and passing it onto the Helm chart. The minio tenant will have this new user, in addition to the regular root user. With this, the behaviour that the krew plugin had is preserved.
Additionally, removes reference to the ``kubectl-minio`` plugin since it doesn't exist anymore.
(cherry picked from commit 8340271ef8930ccc8986779b6aa8eb1096c1cd74) …
=> [Backport 1.29] minio: Adds additional minio tenant user

addons/metallb/disable
When enabling MetalLB, cluster roles and bindings are created. They are not removed when disabling MetalLB. This results in being unable to re-enable MetalLB.
=> MetalLB: Delete cluster roles and bindings on disable

addons/kube-ovn/enable
This PR fixes the AVXTAG not being replaced upon `microk8s enable kube-ovn` based on the original PR: https://github.com/canonical/microk8s-core-addons/pull/261
=> kube-ovn: Fix placeholder not being replaced on enable

addons/kube-ovn/enable
Reverts canonical/microk8s-core-addons#307
=> Revert "kube-ovn: Fix placeholder not being replaced on enable"

addons/kube-ovn/enable
This PR fixes the `__AVXTAG__` placeholder not being replaced (with an empty string) upon `microk8s enable kube-ovn` when the CPU has AVX flags based on the original PR: https://github.com/canonical/microk8s-core-addons/pull/261
=> [Backport 1.31] kube-ovn: Fix placeholder not being replaced on enable

tests/validators.py
Reverting https://github.com/canonical/microk8s-core-addons/commit/92023071bd07a4fc20d643e2dbcf6247870b2d77 which got changed incorrectly
=> Revert cis validator change for strict difference

.github/workflows/backport.yaml
Currently, the backports are being made by the ``github-actions`` user, which means that other workflows are not triggered by it, including CI tests, which we want to run.
NOTE: the secret ``BOT_TOKEN`` **must** exist.
Running as a different user will address this issue.
=> actions: Run backport action with a different account

.github/workflows/check-formatting.yml, .github/workflows/run-tests.yml, addons/rook-ceph/plugin/.rook-create-external-cluster-resources.py
black has a new version, and because of this, one of the files needs to be reformatted.
Install pip through apt-get instead.
=> Fixes CI failures

.github/workflows/run-tests.yml, tests/requirements.txt
CI: Pins pytest to 8.3.4 for Test core addons
Currently, the "Test core addons" job fails because the ``test_cis`` test fails, having 2 more warnings than expected.
Those warnings are from ``microk8s kube-burner``, which has the following new warnings (the checks were passing before):
```
[WARN] 2.3 Ensure that the --auto-tls argument is not set to true (Automated)
[WARN] 2.6 Ensure that the --peer-auto-tls argument is not set to true (Automated)
```
Those warnings appear because the commands used for checking them fail:
```
2.3 audit test did not run: failed to run: "/bin/ps -ef | /bin/grep k8s-dqlite | /bin/grep -v grep", output: "", error: exit status 1
2.6 audit test did not run: failed to run: "/bin/ps -ef | /bin/grep k8s-dqlite | /bin/grep -v grep", output: "", error: exit status 1 …
```
=> CI: use pyenv with pinned pytest 8.3.4

.github/workflows/run-tests.yml, addons/rook-ceph/plugin/.rook-create-external-cluster-resources.py, tests/requirements.txt
Backport of https://github.com/canonical/microk8s-core-addons/pull/321
=> [Backport 1.30] CI: use pyenv with pinned pytest 8.3.4

.github/workflows/run-tests.yml, addons/rook-ceph/plugin/.rook-create-external-cluster-resources.py, tests/requirements.txt
Backport of https://github.com/canonical/microk8s-core-addons/pull/321
=> [Backport 1.31] CI: use pyenv with pinned pytest 8.3.4

.github/workflows/run-tests.yml, addons/rook-ceph/plugin/.rook-create-external-cluster-resources.py, tests/requirements.txt
=> [Backport 1.29] CI: use pyenv with pinned pytest 8.3.4 

.github/workflows/run-tests.yml, addons/rook-ceph/plugin/.rook-create-external-cluster-resources.py, tests/requirements.txt
=> [Backport 1.28] CI: use pyenv with pinned pytest 8.3.4 

addons/ingress/enable
=> [1.32] fix: update ingress-nginx to 1.11.5

addons/ingress/enable
=> [1.30] fix: update ingress-nginx to 1.11.5

addons/ingress/enable
=> fix: update ingress-nginx to 1.12.1

addons/dns/coredns.yaml, addons/dns/enable
Regarding our [issue 252: extending DNS addon args](https://github.com/canonical/microk8s-core-addons/issues/252)
We would like to add a third argument to DNS addon setup which we use in launch configurations to customize the cluster domain (default keeps: cluster.local).
Tested successfully with MicroK8s 1.29/stable on a single node with Ubuntu 22.04 and launch configuration.
=> Dns domain argument

addons/ingress/enable
(cherry picked from commit 64b81b9b3545abd6eaf96e868f764202990a8d53)
=> [1.28] fix: update ingress-nginx to 1.11.5 (#330)

addons/ingress/enable
(cherry picked from commit 64b81b9b3545abd6eaf96e868f764202990a8d53)
=> [1.29] fix: update ingress-nginx to 1.11.5 (#330)

.github/workflows/run-tests.yml, addons/kube-ovn/disable, addons/kube-ovn/enable, addons/kube-ovn/install.sh, tests/templates/nginx-svc.yaml, tests/test-addons.py, tests/utils.py, tests/validators.py
Updated the `install.sh` and `disable` scripts, based on the upstream versions.
=> kube-ovn: Upgrade to v1.13.8

addons/rook-ceph/README.md, addons/rook-ceph/enable, addons/rook-ceph/plugin/.rook-create-external-cluster-resources.py, addons/rook-ceph/plugin/.rook-import-external-cluster.sh, addons/rook-ceph/plugin/connect-external-ceph, tests/validators.py
Reviewer notes regarding this update:
- `.rook-create-external-cluster-resources.py`: it now matches upstream's v1.16.6 script (the `--keyring` PR merged upstream, as well as IPv6 support).
- `connect-external-ceph`: if an error occurs while calling `.rook-create-external-cluster-resources.py`, we now log its `stdout` and `stderr`, which were not logged previously. This demystifies potentials errors.
- `validators.py`: in `validate_rook_ceph_integration`, we now enable `prometheus`, which is now required, as noted below.
Notable updates:
- `.rook-create-external-cluster-resources.py`: If a `--monitoring-endpoint` option is not given, the script will try to automatically find one. If it is not found, an `ExecutionFailureException` is now raised (it was not previously).
*Also verify you …
=> rook-ceph: Update addon to v1.16.6

.github/workflows/run-tests.yml, addons/kube-ovn/disable, addons/kube-ovn/enable, addons/kube-ovn/install.sh, tests/templates/nginx-svc.yaml, tests/test-addons.py, tests/utils.py, tests/validators.py
There are a few issues with the `kube-ovn` addon:
- While enabling, it may timeout while waiting for the Calico pods to disappear. This may happen if its service account / cluster role / cluster role binding gets deleted, it can no longer fetch `ClusterInformation`. We're now removing them beforehand, and waiting for them to disappear.
- The `CNI_CONF_DIR` should be `/var/snap/microk8s/current/args/cni-network`.
- When disabling, we should remove the `01-kube-ovn.conflist` file from `$CNI_CONF_DIR`, otherwise `kube-ovn` may be used for future pods, even though the `kube-ovn` addon is not enabled.
- When disabling, reenable the default CNI and rollout the CoreDNS deployment, so it can use the default CNI.
Adds kube-ovn addon test. The test will enable the `kube-ovn` addon and test the …
=> [Backport 1.32] Fixes kube-ovn addon

tests/test-addons.py
kube-ovn tests require specific environment configuration for `pod-cidr` and `service-cidr`, disable unless explicitly asked for.
=> chore: skip kube-ovn tests unless required
