canonical/microk8s-core-addons

- addons.yaml
- addons/community/disable
- addons/community/enable
With this addon the user can enable/disable the community repository.
> An addon to enable the community repository

- addons.yaml
- addons/dns/coredns.yaml
> upgrade coredns to v1.9.0

- addons/mayastor/disable
Closes https://github.com/canonical/microk8s/issues/3060
> Make a few retries when getting the mayastor pools in the cluster

- addons/gpu/enable
> [Backport 1.24] Update GPU operator

- .github/workflows/check-formatting.yml
- addons.yaml
- addons/cert-manager/cert-manager.yaml
- addons/cert-manager/disable
- addons/cert-manager/enable
- tests/templates/cert-manager-aio-test.yaml
- tests/test-addons.py
- tests/validators.py
Implement cert-manager addon and tests
Currently in draft to get the CI right. Also pending a decision on the final implementation notes.
> Cert-Manager addon

- tests/validators.py
Backport of canonical/microk8s-core-addons#53 to 1.24
> Cleanup stray kubectl after portforward test

- addons.yaml
- addons/gpu/disable
- addons/gpu/enable
Backport https://github.com/canonical/microk8s-core-addons/pull/55
> GPU addon update - backport to 1.24

- addons/hostpath-storage/storage.yaml
- addons/mayastor/chart/values.yaml
Using a busybox version we know it works.
See https://github.com/docker-library/busybox/issues/48
> Use busybox 1.28.4

- .github/workflows/check-formatting.yml
- addons.yaml
- addons/kube-ovn/crd.yaml
- addons/kube-ovn/disable
- addons/kube-ovn/enable
- addons/kube-ovn/hooks/reconcile
- addons/kube-ovn/kube-ovn.yaml
- addons/kube-ovn/ovn-template.yaml
* [ x] Read the [contributions](https://github.com/ubuntu/microk8s/blob/master/CONTRIBUTING.md) page.
* [x ] Submitted the [CLA form](https://ubuntu.com/legal/contributors/agreement), if you are a first time contributor.
Tested on ARM64/AMD64 Jammy/Focal
> Kube OVN addon

- addons/hostpath-storage/storage.yaml
- addons/mayastor/chart/values.yaml
> Use busybox 1.28.4 (#63)

- addons/ingress/ingress.yaml
closes https://github.com/canonical/microk8s/issues/3158
will be able to revert some of the fixes made in https://github.com/garden-io/garden/pull/2907
> Add ingressClass with the name "nginix"

- tests/test-addons.py
> Fix tests for Helm

- .github/workflows/run-tests.yml
Run tests for classic and strict branches in parallel.
> Run strict and classic tests in parallel

- addons.yaml
- addons/hostpath-storage/storage.yaml
- tests/templates/pvc-pvdir.yaml
- tests/test-addons.py
- tests/validators.py
Update hostpath provisioner to 1.4.0
- https://github.com/canonical/hostpath-provisioner/pull/5
> update hostpath storage addon to 1.4.0

- addons/observability/enable
> Set endpoints of kubeControllerManager and kubeScheduler so that prometheus can scrape the informations

- addons/observability/enable
> Fix observability for multi-node cluster

- .github/workflows/run-tests.yml
Configure the tests in the 1.25 branch
> Configure testing for 1.25

- addons.yaml
- addons/minio/disable
- addons/minio/enable
- addons/minio/kubectl-minio
- tests/test-addons.py
- tests/validators.py
Add MicroK8s minio addon. Work in progress
> MinIO addon (Object storage)

- addons/gpu/enable
> Update GPU operator to v22.9.0

- addons.yaml
- addons/hostpath-storage/storage.yaml
Includes https://github.com/canonical/hostpath-provisioner/pull/7
> update hostpath-provisioner to 1.4.1

- addons.yaml
- addons/hostpath-storage/storage.yaml
> [Backport 1.25] Bump hostpath-provisioner to 1.4.2

- .github/workflows/run-tests.yml
As part of branching the 1.26 code.
> Configure GH testing to be against 1.26

- addons/cert-manager/cert-tester.yaml
- addons/cert-manager/enable
> Enable cert-manager waits for cert-manager to be operational

- addons.yaml
- addons/gpu/enable
- tests/test-addons.py
- tests/utils.py
Bumped GPU operator to 22.9.1 to fix issues with containerd
> Bump GPU operator addon to 22.9.1

- addons.yaml
- addons/ingress/enable
- addons/ingress/ingress.yaml
> Update ingress to v1.5.1 - Backport #132 to 1.24

- addons.yaml
- addons/ingress/enable
- addons/ingress/ingress.yaml
> Backport #132 to 1.25

- addons.yaml
- addons/ingress/enable
- addons/ingress/ingress.yaml
> Backport #132 to 1.26

- addons.yaml
- addons/ingress/enable
- addons/ingress/ingress.yaml
> Backport ingress bump v1.5.1 to 1.22-eksd

- addons.yaml
- addons/ingress/enable
- addons/ingress/ingress.yaml
> Backport ingress bump v1.5.1 to 1.23-eksd

- addons.yaml
- addons/ingress/enable
- addons/ingress/ingress.yaml
> Backport ingress bump v1.5.1 to 1.24-eksd

- .github/workflows/run-tests.yml
- tests/test-addons.py
> Drop sh from tests (#153)

- addons/metallb/enable
> [Backport 1.25] ensure metallb addon properly creates the address pool

- addons/observability/enable
> [1.26] Pin helm chart versions for addons

- addons/observability/enable
> [1.25] Pin helm chart versions for addons

- addons/observability/enable
> [1.24-eksd] Pin helm chart versions for addons

- addons/observability/enable
> [1.23-eksd] Pin helm chart versions for addons

- addons/observability/enable
> [1.22-eksd] Pin helm chart versions for addons

- .github/workflows/run-tests.yml
- addons/dns/coredns.yaml
- addons/dns/enable
- addons/metrics-server/disable
- addons/metrics-server/enable
- addons/metrics-server/metrics-server.yaml
This PR introduces the necessary changes for 1.25-eksd.
> EKS-D patches and configuration for 1.25-eksd

- tests/templates/mayastor-pvc.yaml
Fix storage class referenced in mayastor test
> Fix storage class for mayastor test

- addons/mayastor/chart/values.yaml
- tests/templates/mayastor-pvc.yaml
Backport #175, #174 to 1.26 branch
> [1.26] Backport Mayastor fixes

- addons/mayastor/chart/values.yaml
- tests/templates/mayastor-pvc.yaml
Backport #174, #175 to 1.24 branch
> [1.24] Backport Mayastor fixes

- .github/workflows/check-formatting.yml
- .github/workflows/cla-check.yml
- .github/workflows/run-tests.yml
> Initialize 1.27 branch

- addons/cis-hardening/README.md
- addons/cis-hardening/eventconfig.yaml
Increace the event rate limit set by the CIS hardening addon.
> Increate the eventsratelimit set by default

- .github/workflows/check-formatting.yml
- addons/cis-hardening/cfg/cis-1.24-microk8s/master.yaml
Although these two checks are passing on gh actions they do not pass in some local runs. This PR simplifies the checks.
> Simplify the etcd dirs ownership and permissions check

- addons/cis-hardening/README.md
- addons/cis-hardening/disable
- addons/cis-hardening/enable
- addons/cis-hardening/kube-apiserver-to-kubelet.yaml
- addons/cis-hardening/utils.py
- tests/validators.py
This PR properly configures the kubelet webhook auth mode. We are creating the kubelet cert for the node we are going to be on and we also set the right RBAC rules. On the latest releases (latest track) these are properly configured but we also need to handle deployments that got refreshed to this version. Therefor we have this PR.
> Handle webhook kubelet auth-mode

- addons.yaml
- addons/dns/coredns.yaml
- addons/ingress/enable
- addons/metrics-server/metrics-server.yaml
Update:
Coredns to 1.10.1
Metrics server to 0.6.3
Ingress to 1.8.0
Results of this PR  are also found in https://github.com/canonical/microk8s/pull/4031
> Update core addons

- addons/mayastor/chart/templates/mayastor-1-sc.yaml
- addons/mayastor/chart/templates/mayastor-2-sc.yaml
- addons/mayastor/chart/templates/mayastor-3-sc.yaml
- Set reclaim policy to `Retain` (default is `Delete`)
- Add `mayastor-2` storage class (with 2 replicas)
> Mayastor fixes

- addons/mayastor/chart/templates/mayastor-1-sc.yaml
- addons/mayastor/chart/templates/mayastor-2-sc.yaml
- addons/mayastor/chart/templates/mayastor-3-sc.yaml
> [Backport 1.26] Mayastor fixes

- .github/workflows/check-formatting.yml
- .github/workflows/run-tests.yml
- addons/mayastor/chart/templates/mayastor-1-sc.yaml
- addons/mayastor/chart/templates/mayastor-2-sc.yaml
- addons/mayastor/chart/templates/mayastor-3-sc.yaml
> [Backport 1.27] Mayastor fixes

- addons.yaml
- addons/rook-ceph/README.md
- addons/rook-ceph/disable
- addons/rook-ceph/enable
- addons/rook-ceph/plugin/.rook-create-external-cluster-resources.py
- addons/rook-ceph/plugin/.rook-import-external-cluster.sh
- addons/rook-ceph/plugin/connect-external-ceph
- tests/test-addons.py
- tests/validators.py
Based on and replaces #198 
- add new `rook-ceph` addon
- implement `microk8s connect-external-ceph` command
- automatically discover and integrate with microceph, if installed
> Add Rook-Ceph addon, and connect-external-ceph script

- addons/mayastor/chart/templates/mayastor-rbac.yaml
Closes https://github.com/canonical/microk8s/issues/4112
> Fx mayastor rbac rules

- addons/mayastor/chart/templates/mayastor-rbac.yaml
> [Backport 1.27] Fix mayastor rbac rules

- addons/metallb/crd.yaml
- addons/metallb/metallb.yaml
Upgrade metallb manifests to v0.13.10
Metallb provides their yaml as one single file but I split it into the same parts to keep with the current method
> upgrade metallb to v0.13.10

- addons/rook-ceph/README.md
- addons/rook-ceph/plugin/.rook-import-external-cluster.sh
Ensure the default storage classes are created with `reclaimPolicy: Retain`
cc @simskij
> Set reclaimPolicy: Retain for ceph external clusters

- addons/rook-ceph/README.md
- addons/rook-ceph/plugin/.rook-import-external-cluster.sh
Reverts canonical/microk8s-core-addons#224
> Revert "Set reclaimPolicy: Retain for ceph external clusters"

- addons/cis-hardening/README.md
- addons/cis-hardening/enable
Add more information on the additional configs that might be needed for CIS hardening.
Fixes: https://github.com/canonical/microk8s/issues/4177
> Add suggested system configs for CIS hardening

- addons/cis-hardening/README.md
- addons/cis-hardening/enable
Backport https://github.com/canonical/microk8s-core-addons/pull/232
> Add suggested system configs (#232)

- addons/metallb/crd.yaml
- addons/metallb/disable
- addons/metallb/metallb.yaml
* Revert Metallb upgrade to v0.13.10
* Explicitly delete validating webhook configuration
> Revert Metallb upgrade

- tests/templates/microceph.yaml
- tests/test-addons.py
- tests/validators.py
Integration test for MicroCeph that would install a ceph cluster with three disks and try to spawn some pods using the respective storage classes.
> MicroCeph integration test

- addons/gpu/enable
Bump gpu-operator version to v23.9.1
> [Backport 1.26] Bump gpu-operator version to v23.9.1

- addons/gpu/enable
Bump gpu-operator version to v23.9.1
> [Backport 1.27] Bump gpu-operator version to v23.9.1

- addons/gpu/enable
- addons/rook-ceph/plugin/.rook-create-external-cluster-resources.py
Bump gpu-operator version to v23.9.1
> [Backport 1.28] Bump gpu-operator version to v23.9.1

- addons/nvidia/enable
- addons/rook-ceph/plugin/.rook-create-external-cluster-resources.py
Bump gpu-operator version to v23.9.1
> Bump gpu-operator version to v23.9.1

- addons/nvidia/enable
This is a backport of https://github.com/canonical/microk8s-core-addons/pull/270 into 1.29
> Fix the --set-as-default-runtime deprecation warning (#270)

- addons/kube-ovn/crd.yaml
- addons/kube-ovn/enable
- addons/kube-ovn/kube-ovn-template.yaml
- addons/kube-ovn/ovn-template.yaml
this PR is a follow up on https://github.com/canonical/microk8s-core-addons/pull/261
> Fix kube-ovn avx cpu flag

- addons/ingress/enable
Update nginx version to v1.11.2
> Update nginx version to v1.11.2

- .github/workflows/cla-check.yml
(cherry picked from commit 44817d2a899c8829f1e6e1068b3287e4d0a29374)
Backported from: https://github.com/canonical/microk8s-core-addons/pull/275
> update cla checker

- addons/nvidia/enable
> Update Default GPU Operator Version

- addons/metallb/crd.yaml
- addons/metallb/metallb.yaml
Based on the
``https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml`` manifest.
> metallb: Update addon to v1.14.9

- addons.yaml
- addons/dns/coredns.yaml
Update coredns to `v1.12.1`
Update old versions in `addons.yaml` to reflect what's being installed.
> feat: update addons versions and update list

- tests/test-addons.py
(cherry picked from commit dd1c33f03117d6dfbebd196e3a14dc2c6578eb39)
> [1.32] chore: skip kube-ovn tests unless required (#345)
